### ISSUE TITLE
Download only specified timeframe

### ISSUE THREAD

**Issue by ElFrogster** [NickvisionApps/TubeConverter#105]
Feature suggestion:
Allowing to specify a timeframe of the video to download might be a useful feature. It could for example be useful for people who only want to download a specific segment of a several hours long video without having to use the bandwidth to download the whole thing.

**Comment by fsobolev** [comment]
https://www.reddit.com/r/youtubedl/wiki/howdoidownloadpartsofavideo/
An example from this article works with CLI, so we'll be able to implement it.

**Comment by nlogozzo** [comment]
What should the UI be? Should it ne another row in the dialog where the user can simply set a start timestamp and an off timestamp and we'll convert it to seconds and pass it to ytdlp?

**Comment by fsobolev** [comment]
> What should the UI be? Should it ne another row in the dialog where the user can simply set a start timestamp and an off timestamp and we'll convert it to seconds and pass it to ytdlp?

Having an additional row for each item in a playlist seems inconvenient to me. I think we can add a button in rows (maybe with `edit-cut` icon) that will open a popover with entries to set timestamps and a label to show errors in case the data is not valid:
1. text doesn't look like timestamp or a number of seconds
2. start timestamp > end timestamp
3. end timestamp > length of media

Also we should disable entries and show a message if a file in the selected format is only available through DASH protocol (can't be used to download part of video).
Take note that this feature works by using ffmpeg as фт external downloader, so #29 should disable partial downloading.

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/TubeConverter/releases/tag/2023.6.1-rc1
