### ISSUE TITLE
[Windows][Packaging] Add app to a scoop bucket (e.g. extras)

### ISSUE THREAD

**Issue by TayouVR** [NickvisionApps/TubeConverter#107]
scoop is a windows package manager, that I and many other users use to install and update applications.
https://scoop.sh/

**Comment by nlogozzo** [comment]
Tube Converter is a packaged-msix windowsappsdk app. I don't think it can be published to any other packaging service besides the Microsoft Store, since it isn't a traditional desktop application.

**Comment by nlogozzo** [comment]
> also maybe you could offer the .msix builds as releases or build artifacts in actions for direct download for the people that would prefer that?

CI actions now build windows msix files for you to download: https://github.com/nlogozzo/NickvisionTubeConverter/actions/runs/4681172776

I'll start attaching them to releases as well :)

**Comment by nlogozzo** [comment]
Manually builds are now attached to releases: https://github.com/NickvisionApps/TubeConverter/releases/tag/2023.4.2

Closing for now as I won't be maintaining a scoop bucket, feel free if you'd like to maintain it for us, but I will continue to offer manually msix packages for those who don't want to use the store.

**Comment by aliesbelik** [comment]
ScoopInstaller/Extras#15267

**Comment by lolmaus** [comment]
Existing Scoop repos are not maintained.

Please maintain your own. Please reopen the issue. 🙏
