### ISSUE TITLE
Subtitles language filter is too restrictive

### ISSUE THREAD

**Issue by fsobolev** [NickvisionApps/TubeConverter#162]
> Regarding subtitles, the problem is that subtitles for this video have "deu" language code, but in TC we filter subtitles to download only ones for English and system language - that can be "de", but not "deu".

_Originally posted by @fsobolev in https://github.com/nlogozzo/NickvisionTubeConverter/issues/160#issuecomment-1496720567_

What I propose: check if subtitles are available in system language and if yes then download only them, otherwise download all subtitles. Also add a new setting to always download all subtitles.

**Comment by soumyaDghosh** [comment]
Yup, I'm aware, but this seems tough. I'm learning though, this exam is just crambling, also the snap seems buggy.

**Comment by nlogozzo** [comment]
No worries, take your time :) feel free to message me with any questions. 

I'm also in exam week so I understand...I probably won't get any real coding done until next week 🙃

**Comment by nlogozzo** [comment]
> Mine will be from the 3rd week of May(practicals) & from June 1 to 20 theories
> 

Oof that sounds like a lot... good luck!!

**Comment by soumyaDghosh** [comment]
Same to you! Hope github doesn't sue for having chit chats in github issue! LOL!

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/TubeConverter/releases/tag/2023.6.1-rc1
