### ISSUE TITLE
Crashes with Good and Best quality

### ISSUE THREAD

**Issue by fsobolev** [NickvisionApps/TubeConverter#189]
Hi, I still have the same issue using 2023.4.1 (flatpak)

              One addition maybe is quality option.

              It crashes with Good and Best, but has no problem when choosing Worst - then everything works correctly.
              Reproducible: always.

_Originally posted by @ekasprzak in https://github.com/nlogozzo/NickvisionTubeConverter/issues/130#issuecomment-1506858233_

**Comment by fsobolev** [comment]
@ekasprzak Could you please specify when exactly crash happens: immediately after download started, when it finishes or at some other point?
Also console output will really help.
```
flatpak run org.nickvision.tubeconverter
```
And would be nice if you can check whether the problem still exists in [latest beta](https://github.com/nlogozzo/NickvisionTubeConverter/releases/tag/2023.4.2-beta1).

**Comment by nlogozzo** [comment]
I don't know why this would be happening when we wrapped everything in `g_main_context_invoke`...maybe I missed something...

**Comment by fsobolev** [comment]
> I didn't want to open a new issue as the problem is the same as in #130, (I just added some additional info about quality).
> Same in description - "UI hangs and then closes itself" and exactly the same output from console:

Hm... Hard for me to imagine how it can depend on quality, that's why I thought it's a separate issue.

**Comment by ekasprzak** [comment]
> > I didn't want to open a new issue as the problem is the same as in #130, (I just added some additional info about quality).
> > Same in description - "UI hangs and then closes itself" and exactly the same output from console:
> 
> Hm... Hard for me to imagine how it can depend on quality, that's why I thought it's a separate issue.

Yeah, I  get it.
 Just to be fully confirm it, I triple checked it:

One, the same youtube video:
3 attempts with Best quality - all crashed with above error
3 attempts with Good quality - all crashed with above error
3 attempts with Worst quality - all success

**Comment by nlogozzo** [comment]
> One, the same youtube video:

Could you send us the link of the video you were trying to download?

> And would be nice if you can check whether the problem still exists in [latest beta](https://github.com/nlogozzo/NickvisionTubeConverter/releases/tag/2023.4.2-beta1).

And yes, if you could try with the latest beta too see if it still happens.

**Comment by MetalDroid** [comment]
> @ekasprzak Could you please specify when exactly crash happens: immediately after download started, when it finishes or at some other point? Also console output will really help.
> 
> ```
> flatpak run org.nickvision.tubeconverter
> ```
> 
> And would be nice if you can check whether the problem still exists in [latest beta](https://github.com/nlogozzo/NickvisionTubeConverter/releases/tag/2023.4.2-beta1).

The same thing happens to me, and always at exactly the same point, when the download ends and it starts to generate the final file.

This is the console output:

```
➜  ~ flatpak run org.nickvision.tubeconverter

(NickvisionTubeConverter.GNOME:2): Gtk-CRITICAL **: 15:00:58.237: gtk_widget_get_parent: assertion 'GTK_IS_WIDGET (widget)' failed

(NickvisionTubeConverter.GNOME:2): Gtk-CRITICAL **: 15:00:58.249: gtk_widget_add_css_class: assertion 'GTK_IS_WIDGET (widget)' failed
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.

```

**Comment by nlogozzo** [comment]
> The same thing happens to me, and always at exactly the same point, when the download ends and it starts to generate the final file.

Could you provide the link of the video you were trying to download? As well as the download parameters (file type, quality, embed metadata in preferences, etc...)

**Comment by MetalDroid** [comment]
> > The same thing happens to me, and always at exactly the same point, when the download ends and it starts to generate the final file.
> 
> Could you provide the link of the video you were trying to download? As well as the download parameters (file type, quality, embed metadata in preferences, etc...)

Of course (I used all the default values):

**URL:** `https://www.eitb.eus/es/nahieran/el-conquistador-del-fin-del-mundo/19-temporada-2023-caribe/detalle/8538/217491/`

**File type:** MP4
**Quality:** Best
**Subtitles:** None

**Preferences:** default values (metadata is checked)

Greetings

**Comment by nlogozzo** [comment]
@ekasprzak Did the latest stable, V2023.4.2, fix your crashing issues as well?

**Comment by nlogozzo** [comment]
There is still some random crashing we found but should be fixed with this: https://github.com/NickvisionApps/TubeConverter/actions/runs/4743819541

@ekasprzak If V2023.4.2 doesn't work for you, please try this artifact as well ^

**Comment by ekasprzak** [comment]
> @ekasprzak Did the latest stable, V2023.4.2, fix your crashing issues as well?

Hi, yes, it did, works perfect now, thanks a lot!
