### ISSUE TITLE
Make aria2 configurable

### ISSUE THREAD

**Issue by fsobolev** [NickvisionApps/TubeConverter#198]
@fsobolev I believe having the ability to configure both `-x` and `-k` by the user would be really convenient

_Originally posted by @VarLad in https://github.com/NickvisionApps/TubeConverter/issues/29#issuecomment-1514435164_

**Comment by nlogozzo** [comment]
![image](https://github.com/NickvisionApps/TubeConverter/assets/17648453/f765ad4d-5ea3-4d8b-a14c-6c2c6bc24423)

@VarLad any other preferences you would like to see?

**Comment by VarLad** [comment]
@nlogozzo Not really, thanks for the feature! 
On the other hand, as of the latest version, I see "Media URL (invalid)" for m3u8 stream links. 
This used to work perfectly before (with aria2c enabled). Has there been a change in that?

**Comment by nlogozzo** [comment]
No nothing changed that I know of....FYI @fsobolev 
If you disable aria2c does it work? Maybe something changed with yt-dlp? Could you send the link, I'll try on my end.

**Comment by VarLad** [comment]
@nlogozzo This is one https://devimages.apple.com.edgekey.net/streaming/examples/bipbop_16x9/bipbop_16x9_variant.m3u8

**Comment by nlogozzo** [comment]
@VarLad 
![image](https://github.com/NickvisionApps/TubeConverter/assets/17648453/0e0a3170-92ab-4b9d-8c19-515045a25fe7)

I get this when I try to access the site from the browser. Could be this that's blocking yt-dlp from accessing it. Will do more investigation later....

**Comment by VarLad** [comment]
@nlogozzo My bad, try this http://playertest.longtailvideo.com/adaptive/wowzaid3/playlist.m3u8
Should work with `yt-dlp --external-downloader aria2c --external-downloader-args "aria2c:-x 16 -k 1M" "http://playertest.longtailvideo.com/adaptive/wowzaid3/playlist.m3u8"` as a test

**Comment by VarLad** [comment]
This used to work up until the latest update I guess.

**Comment by nlogozzo** [comment]
@VarLad Found the issue. Fixed with https://github.com/NickvisionApps/TubeConverter/pull/274/commits/ac19df89add87730c7b09a819e26f02745717f18 in #274 . Once that PR is merged, I'll release beta1 that you can use to test.

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/TubeConverter/releases/tag/2023.6.0-beta1

This and m3u8 fixed in ^
