### ISSUE TITLE
Stopping/Retrying Multiple Downloads Not Working --> NEW BACKEND

### ISSUE THREAD

**Issue by nlogozzo** [NickvisionApps/TubeConverter#222]
Working with multiple downloads in terms of stopping and retrying them do not work 100% correctly. 
To solve this, I will be writing a new backend altogether. This will not only fix this issue but it will also fix some architectural design choices that I do not like, such as the actual downloads being managed by the UI rows themselves instead of the backend.

**Comment by DaPigGuy** [comment]
These changes should make it extremely easy to make those action menu items (in)sensitive depending on what's queued/failed, for whoever gets to that change first :slightly_smiling_face:

**Comment by nlogozzo** [comment]
Yes i'm hoping to make a centralized `DownloadManager` API in the backend where all the downloads and information will be handled there instead of needing to query through different lists of rows.

**Comment by nlogozzo** [comment]
One challenge will be however actually creating the rows and giving information to the rows to update, since they will no longer manage the downloads but...i'm sure i'll find something.

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/TubeConverter/releases/tag/2023.5.0-beta1
