### ISSUE TITLE
Installed from Windows Store - Clicking settings immediately crashes

### ISSUE THREAD

**Issue by ScottRFrost** [NickvisionApps/TubeConverter#225]
Not sure what I'm doing wrong or what logs you need, but here's a video

https://user-images.githubusercontent.com/3866418/235474775-358311a3-072b-4eb1-ad8d-e92c2f370058.mp4

Windows 11 Pro 22H2 22621.1555 Ryzen 9 7950X, 32GB RAM

**Comment by ScottRFrost** [comment]
Oh, I guess GitHub still doesn't support HEVC MP4s

https://user-images.githubusercontent.com/3866418/235475661-cc0766dd-1c18-42a7-832e-1d9943adad2b.mp4

**Comment by ScottRFrost** [comment]
Oh, I guess GitHub still doesn't support HEVC MP4s?

Here it is again as a .gif
![TubeConverter](https://user-images.githubusercontent.com/3866418/235475877-71a2ba79-9ee2-4da5-ad1e-9ad3e0727598.gif)

**Comment by nlogozzo** [comment]
Fixed in [V2023.4.2](https://github.com/NickvisionApps/TubeConverter/releases/tag/2023.4.2). 
Microsoft is giving me problems uploading the update that's why it's not there yet.

You can download and install it manually from the releases page for now.
