### ISSUE TITLE
Add option to crop thumbnail to square

### ISSUE THREAD

**Issue by quazar-omega** [NickvisionApps/TubeConverter#237]
Would it be possible to add an option either in the settings or in the download dialog to crop the thumbnail to a square? yt-dlp has that as seen [here](https://github.com/yt-dlp/yt-dlp/issues/429).
It would be especially useful for music coming from YouTube Music

**Comment by quazar-omega** [comment]
I think if placed in the settings it would be better so you could have like a list (user defined?) of domains that you want that option to work on, but that doesn't prevent from having a toggle in the download dialog to override the setting defined behavior

**Comment by nlogozzo** [comment]
Well maybe since like you said you'd use it for sites like YouTube music, we just make it a per download setting so the user can turn it on when they chose and avoid over complicating the feature.

**Comment by nlogozzo** [comment]
Also @fsobolev maybe we can create an Advanced page (similar to currency in account settings for Denaro) that will hold this setting, overwrite files, speed limit, and and any other setting to avoid a super long scrolling dialog.

**Comment by nlogozzo** [comment]
> > Also @fsobolev maybe we can create an Advanced page (similar to currency in account settings for Denaro) that will hold this setting, overwrite files, speed limit, and and any other setting to avoid a super long scrolling dialog.
> 
> The problem is that in Denaro all data can be changed at will, while in TC once download is started options can't be changed, so it's better to show all options on one screen to inform users and make all features easier to discover. I will think how to redesign the dialog.

I think an `Advanced` screen will work because most of the time user's don't change those settings unless they really need to so it's ok to put it on a separate screen. 
I think the features are still easy to discover.

**Comment by fsobolev** [comment]
> I think an `Advanced` screen will work because most of the time user's don't change those settings unless they really need to so it's ok to put it on a separate screen.
> I think the features are still easy to discover.

My current idea is to keep all options on one screen but move playlist to a separate view. This will resolve 3 problems at once: the dialog will not have that much height, playlist will be easier to navigate because it will use much more space and since we'll need a row to switch to playlist view there will be a place to let users know that changing titles affects only filenames (which is not always obvious, see discussion [here](https://github.com/NickvisionApps/TubeConverter/issues/166)).

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/TubeConverter/releases/tag/2023.5.0-rc2

**Comment by quazar-omega** [comment]
Tried it just now, thanks so much!
