### ISSUE TITLE
[Flatpak][Snap] Doesn't show notification and progressbar in dock in Ubuntu

### ISSUE THREAD

**Issue by fsobolev** [NickvisionApps/TubeConverter#243]
> flatpak one is crashing whenever I am adding any link, it validates, then shows me the dialog box, I select start to download and it crashes in ubuntu.

@soumyaDghosh found the bug. The crash is silent. After crash there are empty `log` and `output.log` files.

I can't reproduce it neither in Lubuntu VM nor in Silverblue on real hardware.

**Comment by nlogozzo** [comment]
Could it be something with libunity and the progress on the launcher feature?

**Comment by soumyaDghosh** [comment]
Flatpak crash seems to have been fixed, I tried latest beta, and it worked at par the snap. Not as expected. The issues are same, no progressbar in dock and no notification.

**Comment by fsobolev** [comment]
> The issues are same, no progressbar in dock and no notification.

Wait, are you experiencing these issues with flatpak as well?

**Comment by fsobolev** [comment]
I can confirm that notifications stopped working in flatpak.
But not libunity progress bar, it works as before.

**Comment by nlogozzo** [comment]
Maybe Cake isn't installing dbus correctly?
I remember we removed the Dbus activatable from the .desktop file in the switch, maybe that was a mistake and we need it back.

**Comment by fsobolev** [comment]
> I remember we removed the Dbus activatable from the .desktop file in the switch

I removed it from `desktop.in` because it's then added by Cake in `FinishPublishGNOME`, I did it like this because for Avalonia we wouldn't need dbus activation.
The problem that I see is that it seems nothing calls `SendShellNotification`... Maybe something was removed when you rewrote downloads management?

**Comment by nlogozzo** [comment]
Ah could be...I'm at work rn so I'll check it when I get home.

It's only for when download is completed right? Background apps still works?

**Comment by fsobolev** [comment]
> Background apps still works?

Background status works, but the app doesn't close if it's hidden and all downloads are finished.

**Comment by nlogozzo** [comment]
> but the app doesn't close if it's hidden and all downloads are finished.

That's weird, I don't think I touched any of that code...

**Comment by fsobolev** [comment]
> > but the app doesn't close if it's hidden and all downloads are finished.
> 
> That's weird, I don't think I touched any of that code...

Both operations were in move row callback https://github.com/NickvisionApps/TubeConverter/pull/227/files#diff-b6a1358677be9f4b4c70465692ca2a80b73b5157e32345510051f2332a5b66a0L116

```
            if (box == _completedBox && (!GetFocus()!.GetHasFocus() || !GetVisible()))
            {
                SendShellNotification(new ShellNotificationSentEventArgs(_controller.Localizer[row.FinishedWithError ? "DownloadFinishedWithError" : "DownloadFinished"], string.Format(_controller.Localizer[row.FinishedWithError ? "DownloadFinishedWithError" : "DownloadFinished", "Description"], $"\"{row.Filename}\""), row.FinishedWithError ? NotificationSeverity.Error : NotificationSeverity.Success));
                if (!GetVisible() && !_controller.AreDownloadsRunning && _controller.ErrorsCount == 0)
                {
                    _application.Quit();
                }
            }
```

**Comment by nlogozzo** [comment]
Ah ok my fault then 😆
Will fix when I get home from work...

**Comment by soumyaDghosh** [comment]
Just asking... Was I the only one to notice this! And that also in snap?

**Comment by nlogozzo** [comment]
Yes you were the only one that brought this to our attention. It seemed to be a regression in `V2023.5.0-beta1` when we rewrote the backend, therefore many users probably didn't notice it/nor test it yet...

Good job catching it before stable :)

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/TubeConverter/releases/tag/2023.5.0-rc2

**Comment by fsobolev** [comment]
@soumyaDghosh I didn't manage to test the changes in snap yet, but I hope that libunity progress will be shown now.
