### ISSUE TITLE
Implement Cookies Preference for Login

### ISSUE THREAD

**Issue by nlogozzo** [NickvisionApps/TubeConverter#251]
https://reddit.com/r/youtubedl/w/cookies?utm_medium=android_app&utm_source=share

This will be a global setting in which the user can select a file containing their cookies.

This file will then be passed to yt-dlp which will allow users to download private videos if they're youtube login is stored in the cookies file.

**Comment by fsobolev** [comment]
> This will be a global setting in which the user can select a file containing their cookies.

Since getting files with cookies requires to use an extension for a browser, we could add a section similar to what can be seen in GSConnect.

![image](https://github.com/NickvisionApps/TubeConverter/assets/117388856/3ced111e-6b05-4f47-9499-dc7c8f1d93aa)

**Comment by nlogozzo** [comment]
I was thinking of creating a help flyout on the row explaining how to get your cookies file from the browser, so I can add those buttons there.

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/TubeConverter/releases/tag/2023.6.0-beta1
