### ISSUE TITLE
Add M4A as an available audio format

### ISSUE THREAD

**Issue by Hew-ux** [NickvisionApps/TubeConverter#261]
Please add the ability to download the audio of a video as M4A. MP3 is already available as an option. This is done by converting the downloaded audio file to MP3, whatever it may be originally:

![image](https://github.com/NickvisionApps/TubeConverter/assets/67527064/cd516837-4b9e-4b4a-aade-cc4843e8e389)

A lot of Youtube streams have a native M4A stream available, which wouldn't need further converting, so having the option to download it as an audio file directly would be nice.

I apologise if this functionality has been added in the current beta with its UI overhaul, but I didn't see a specific mention of this in the changelogs specifically.

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/TubeConverter/releases/tag/2023.6.0-beta1
