### ISSUE TITLE
Prevent conversion

### ISSUE THREAD

**Issue by Riksu9000** [NickvisionApps/TubeConverter#263]
I'd like to use this app to simply download video and audio without any conversions. Lossy conversion degrades quality, and lossless conversion often increases the file size unnecessarily. With this I could finally retire my downloader scripts and start using this app.

There could for example be a new selection in the download window for choosing between video or audio only. Then if best quality is chosen, the file type selection is disabled and no conversion will take place. The best format is automatically chosen.

I know converter is in the name of the app, but I personally don't see the point of converting media files in 2023 unless you want to save disk space.

**Comment by nlogozzo** [comment]
Are you using YouTube? YouTube only provides webm and m4a streams...for any other file type a conversion is required

**Comment by fsobolev** [comment]
Conversion doesn't take place for youtube if selected format is mp4 or webm, because youtube provides streams for both formats. But there's merging, because youtube provides audio and video streams separately.

```
$ yt-dlp -F https://www.youtube.com/watch?v=tOm_zATjgqU
[youtube] Extracting URL: https://www.youtube.com/watch?v=tOm_zATjgqU
[youtube] tOm_zATjgqU: Downloading webpage
[youtube] tOm_zATjgqU: Downloading android player API JSON
[youtube] tOm_zATjgqU: Downloading player bbe1b497
[info] Available formats for tOm_zATjgqU:
ID  EXT   RESOLUTION FPS CH │   FILESIZE   TBR PROTO │ VCODEC        VBR ACODEC      ABR ASR MORE INFO
────────────────────────────────────────────────────────────────────────────────────────────────────────────────
sb2 mhtml 48x27        0    │                  mhtml │ images                                storyboard
sb1 mhtml 80x45        0    │                  mhtml │ images                                storyboard
sb0 mhtml 160x90       0    │                  mhtml │ images                                storyboard
599 m4a   audio only      2 │    3.65MiB   31k dash  │ audio only        mp4a.40.5   31k 22k ultralow, m4a_dash
600 webm  audio only      2 │    4.08MiB   34k dash  │ audio only        opus        34k 48k ultralow, webm_dash
139 m4a   audio only      2 │    5.78MiB   49k dash  │ audio only        mp4a.40.5   49k 22k low, m4a_dash
249 webm  audio only      2 │    5.98MiB   51k dash  │ audio only        opus        51k 48k low, webm_dash
250 webm  audio only      2 │    7.43MiB   63k dash  │ audio only        opus        63k 48k low, webm_dash
140 m4a   audio only      2 │   15.33MiB  129k dash  │ audio only        mp4a.40.2  129k 44k medium, m4a_dash
251 webm  audio only      2 │   13.30MiB  112k dash  │ audio only        opus       112k 48k medium, webm_dash
17  3gp   176x144      6  1 │    8.20MiB   69k https │ mp4v.20.3     69k mp4a.40.2    0k 22k 144p
597 mp4   256x144     13    │    3.07MiB   26k dash  │ avc1.4d400b   26k video only          144p, mp4_dash
598 webm  256x144     13    │    2.20MiB   19k dash  │ vp9           19k video only          144p, webm_dash
160 mp4   256x144     25    │    3.58MiB   30k dash  │ avc1.4d400c   30k video only          144p, mp4_dash
278 webm  256x144     25    │    5.62MiB   47k dash  │ vp9           47k video only          144p, webm_dash
133 mp4   426x240     25    │    6.93MiB   59k dash  │ avc1.4d4015   59k video only          240p, mp4_dash
242 webm  426x240     25    │    7.46MiB   63k dash  │ vp9           63k video only          240p, webm_dash
134 mp4   640x360     25    │   12.59MiB  106k dash  │ avc1.4d401e  106k video only          360p, mp4_dash
18  mp4   640x360     25  1 │   37.32MiB  315k https │ avc1.42001E  315k mp4a.40.2    0k 44k 360p
243 webm  640x360     25    │   16.31MiB  138k dash  │ vp9          138k video only          360p, webm_dash
135 mp4   854x480     25    │   19.03MiB  161k dash  │ avc1.4d401e  161k video only          480p, mp4_dash
244 webm  854x480     25    │   24.51MiB  207k dash  │ vp9          207k video only          480p, webm_dash
22  mp4   1280x720    25  2 │ ~ 70.90MiB  585k https │ avc1.64001F  585k mp4a.40.2    0k 44k 720p
136 mp4   1280x720    25    │   53.98MiB  456k dash  │ avc1.4d401f  456k video only          720p, mp4_dash
247 webm  1280x720    25    │   45.60MiB  385k dash  │ vp9          385k video only          720p, webm_dash
298 mp4   1280x720    50    │   93.05MiB  786k dash  │ avc1.4d4020  786k video only          720p50, mp4_dash
302 webm  1280x720    50    │   69.57MiB  588k dash  │ vp9          588k video only          720p50, webm_dash
299 mp4   1920x1080   50    │  181.83MiB 1536k dash  │ avc1.64002a 1536k video only          1080p50, mp4_dash
303 webm  1920x1080   50    │  134.44MiB 1136k dash  │ vp9         1136k video only          1080p50, webm_dash
```

**Comment by Riksu9000** [comment]
I guess my point is that it's not apparent in the app if conversion is taking place. I'd need to know yt-dlp, use the cli for each service and also understand the workings of the app, when this could just be done automatically in the app I think.

**Comment by fsobolev** [comment]
Adding mkv will solve the issue.

**Comment by nlogozzo** [comment]
@Riksu9000 How would you like the app to solve this? 

@fsobolev suggests that:
> A global setting "Disallow conversion". If enabled, instead of list of formats the user will just select "Video" or "Audio", and no options related to format will be passed to yt-dlp, it will just download whatever fits the requested quality (so it will be webm+m4a=mkv videos for youtube, mp4 for some other services, mp3 for bandcamp, etc)

**Comment by Riksu9000** [comment]
This suggestion works for me.

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/TubeConverter/releases/tag/2023.6.0-rc1

**Comment by Riksu9000** [comment]
It seems that thumbnails aren't being embedded when downloading audio with conversions disallowed and embed metadata enabled.

Otherwise the feature seems to work perfectly. Thanks!

**Comment by nlogozzo** [comment]
> It seems that thumbnails aren't being embedded when downloading audio with conversions disallowed and embed metadata enabled.


I know why...will be fixed before stable on Friday :)

**Comment by nlogozzo** [comment]
> It seems that thumbnails aren't being embedded when downloading audio with conversions disallowed and embed metadata enabled.

Fixed with https://github.com/NickvisionApps/TubeConverter/commit/97796af2d5150060d03d658dfa9947813cef80ae. Like I said will be released with the stable version on Friday!
