### ISSUE TITLE
Reduce notifications when downloading a playlist

### ISSUE THREAD

**Issue by KSXGitHub** [NickvisionApps/TubeConverter#272]
## Problem

It's very annoying if the notification appear again and again for every completion on a playlist.

## Suggestion

Only show 1 notification when all videos in a playlist have been completed.

**Comment by fsobolev** [comment]
I think we could add a setting with 3 options to choose from:
1. Show notification for each download (default)
2. Show notification when all downloads completed
3. Disable notifications

**Comment by KSXGitHub** [comment]
> Show notification when all downloads completed

Does "all" refer to just a playlist or all downloads in general. If it's just a playlist, then the language need to be clearer.

**Comment by fsobolev** [comment]
> Does "all" refer to just a playlist or all downloads in general? If it's just a playlist, then the language need to be clearer.

All downloads in general. In other words, when there are no more downloads in "Downloading" section, show notification.

**Comment by nlogozzo** [comment]
![image](https://github.com/NickvisionApps/TubeConverter/assets/17648453/15b6a421-d620-4291-bdce-620671fed510)

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/TubeConverter/releases/tag/2023.6.0-beta1
