### ISSUE TITLE
Error number 13 Permission Denied

### ISSUE THREAD

**Issue by dln949** [NickvisionApps/TubeConverter#276]
Tube Converter (flatpak, installed as system) 2023.5.0 on Ubuntu 22.04.  

Any Youtube URL I try always fails with this error:  ERROR: [Errno 13] Permission denied: '/run/user/1000/doc

For example, 
[MoveFiles] Moving file "/home/main1/.var/app/org.nickvision.tubeconverter/config/Nickvision/Nickvision Tube Converter/temp/6eec70e3-3aaf-4c13-a4d1-82c9901fa4c0/Coin\ Hay\ from\ Men\ at\ Work\ --\ Down\ Under\ \(Live\)\ --\ Look\ who\ the\ drummer\ is!\.mp4" to "/run/user/1000/doc/b02a45d9/Downloads/Coin\ Hay\ from\ Men\ at\ Work\ --\ Down\ Under\ \(Live\)\ --\ Look\ who\ the\ drummer\ is!\.mp4"
ERROR: [Errno 13] Permission denied: '/run/user/1000/doc/b02a45d9/Downloads/Coin\\ Hay\\ from\\ Men\\ at\\ Work\\ --\\ Down\\ Under\\ \\(Live\\)\\ --\\ Look\\ who\\ the\\ drummer\\ is!\\.mp4' for this URL:  [https://www.youtube.com/watch?v=UEx9Mpu3J3o](url)

**Comment by nlogozzo** [comment]
If you upgrading from previous versions on Tube Converter, I would try reselecting your `Save Folder` in the Add Download dialog and see if that fixes permissions. 

If not, I recommend downloading `Flatseal` and granting Tube Converter filesystem access to the locations you'd like to download videos.

**Comment by dln949** [comment]
Granting "home" permissions in Flatseal solved this problem, thanks.
