### ISSUE TITLE
More Circle Tweaks

### ISSUE THREAD

**Issue by nlogozzo** [NickvisionApps/TubeConverter#283]
Source: https://gitlab.gnome.org/Teams/Circle/-/issues/128#note_1756604

- [x] I wouldn't show a toast here for the autofill, it's a bit distracting. I think just auto-populating by itself should be fine, or maybe a static label below the entry?
- [x] I had a crash after pausing and re-starting a download

**Comment by nlogozzo** [comment]
Update: https://gitlab.gnome.org/Teams/Circle/-/issues/128#note_1756804

- [ ] The "Add Download" dialog doesn't seem to be resizable, is there a reason for this? It's a shame, because it means it doesn't work on mobile, even though the layout would be well-suited for it.
- [ ] The description on the empty state shouldn't have a period at the end
- [ ] The way this row is implemented is a bit odd, usually arrows on the right aren't buttons with separate hover states

**Comment by nlogozzo** [comment]
@fsobolev Could you take care of this?
>  The "Add Download" dialog doesn't seem to be resizable, is there a reason for this? It's a shame, because it means it doesn't work on mobile, even though the layout would be well-suited for it.

I tried removing the `resizable` field and it caused a bunch of lines to be added everywhere when I validated a URL.

Even those the `resizable` field is false, doesn't the window grow and shrink for the device, meaning it will still work on mobile?

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/TubeConverter/releases/tag/2023.6.0-beta2

**Comment by birros** [comment]
> The "Add Download" dialog doesn't seem to be resizable, is there a reason for this? It's a shame, because it means it doesn't work on mobile, even though the layout would be well-suited for it.

Sorry to comment this old closed issue, but it's about a design issue I've just faced.

The dialog window is too small when I want to select videos from a playlist, particularly when many have a long prefix in their title. It's hard to differentiate them. It would be more useful to have a resizable window on large screens.

I suppose this concerns the next line:
https://github.com/NickvisionApps/Parabolic/blob/2ab34a7388b27a5882daaf51f66c50b954eb9825/NickvisionTubeConverter.GNOME/Blueprints/add_download_dialog.blp#L8

Is there any reason why `resizable` is still set to `false`?

---

Thx for this well-designed, high-performance and stable `yt-dlp` frontend 🎉

**Comment by nlogozzo** [comment]
> Is there any reason why resizable is still set to false?

@fsobolev 

> Thx for this well-designed, high-performance and stable yt-dlp frontend 🎉

♥️

**Comment by fsobolev** [comment]
> > Is there any reason why resizable is still set to false?
> 
> @fsobolev

There were some issues when the window was resizable, but I don't remember exactly, will try again.
