### ISSUE TITLE
New Autofill button in "Add Download" menu

### ISSUE THREAD

**Issue by Karol739** [NickvisionApps/TubeConverter#285]
Hello,
According to the discussion right here: https://gitlab.gnome.org/Teams/Circle/-/issues/128#note_1756604 about autofilling URL from a clipboard, I would suggest making a separate button for that. The previous way of autofilling - the "real autofill" would be accessible in the preferences, though.
When clicking that button, the data from clipboard would be obtained and checked to see if that's the real URL and then - filled.
The previous way of "real" autofilling would be accessible as an option in app settings. I'd suggest making a new switch for that. The option would work just like the function works today.
Here's the simple scheme of the button positioning with URL field on the left. This simple scheme isn't definitely perfect look-wise, but it's clear (for me).

Have a nice day!
![autofill scheme](https://github.com/NickvisionApps/TubeConverter/assets/65565502/6568621d-78ed-4002-ae07-d33023a97551)

**Comment by fsobolev** [comment]
I don't get what's an advantage of having a button over autofill that happens automatically when you open the dialog, like it's implemented currently.

**Comment by nlogozzo** [comment]
Yeah you can test the implementation in [V2023.6.0-beta](https://github.com/NickvisionApps/TubeConverter/releases/tag/2023.6.0-beta1) but I think it's fine the way it is.
