### ISSUE TITLE
Save save folder location

### ISSUE THREAD

**Issue by piegamesde** [NickvisionApps/TubeConverter#307]
I'd like to save downloaded videos in a separate folder, however it is tedious setting the path again for each download. It would be good if the application would save the path for the next use, or alternatively provide a dedicated preference for it.

**Comment by fsobolev** [comment]
The app does remember the last save folder and reuses it. Does it require for you to select folder every time?

**Comment by nlogozzo** [comment]
Yes this feature is already implemented and seems to not be working for you...Could you provide us with some more information?

Where did you install Tube Converter from? What distro and version are you using?

**Comment by piegamesde** [comment]
Huh, I cannot reproduce anymore on this machine. Was this feature implemented recently perhaps?

**Comment by nlogozzo** [comment]
Nope it's been there from the beginning 😆

**Comment by nlogozzo** [comment]
Just curious... where did you install TC from? Snap? Flatpak? Other?

**Comment by piegamesde** [comment]
I installed it via Arch Linux AUR.

**Comment by nlogozzo** [comment]
Interesting...glad it's working now tho :)
