### ISSUE TITLE
Add support for yt-dlp usernames and passwords

### ISSUE THREAD

**Issue by mossymossmoss** [NickvisionApps/TubeConverter#322]
yt-dlp provides support for the `--username` and `--password` tags in order to download from a website that requires an account. The recent addition of the cookie support works for some sites, but in cases such as https://nebula.tv/ a passed username and password is required to download

**Comment by nlogozzo** [comment]
This will probably go into `Advanced Options` per download, as usernames and passwords change between sites so it doesn't make sense to add it as a global option in `Preferences`

**Comment by fsobolev** [comment]
> This will probably go into `Advanced Options` per download, as usernames and passwords change between sites so it doesn't make sense to add it as a global option in `Preferences`

It makes sense to add password manager-like functionality, so the user saves login-password pairs in global settings and then if needed selects one in advanced option.

**Comment by nlogozzo** [comment]
> so the user saves login-password pairs in global settings

The problem is this could be a security risk as usernames and passwords are not encrypted so they will be stored as plain text in the config.json file for anyone to access.

This way it's typed it every time and only used in memory when needed and once the download finishes it is gone.

Plus, if a username/password for a website changes, how will the user change that...don't want to make a Video Downloader into a full Password Manager as well 🥲

**Comment by fsobolev** [comment]
> The problem is this could be a security risk as usernames and passwords are not encrypted so they will be stored as plain text in the config.json file for anyone to access.

We could for example use [ProtectedData](https://learn.microsoft.com/en-us/dotnet/api/system.security.cryptography.protecteddata?redirectedfrom=MSDN&view=windowsdesktop-7.0) class and save entropy with [libsected](https://gnome.pages.gitlab.gnome.org/libsecret/) (or just use libsecret for everything).

> Plus, if a username/password for a website changes, how will the user change that...

A button to remove a pair wouldn't take much space 😄

**Comment by nlogozzo** [comment]
> We could for example use [ProtectedData](https://learn.microsoft.com/en-us/dotnet/api/system.security.cryptography.protecteddata?redirectedfrom=MSDN&view=windowsdesktop-7.0) class

![image](https://github.com/NickvisionApps/TubeConverter/assets/17648453/ab953e42-059f-4ee8-9fbc-fe7367c57d1e)

> A button to remove a pair wouldn't take much space

You're right, but I honestly think it's more of a hassle then it's worth. I'm sure some people will complain saying why do I have to remove the pair if just my password changed and I just wanna change that instead of both username and password on reentry. And other complaints...

Like I said, think it's just best to have them enter username and password when needed and call it a day.

**Comment by fsobolev** [comment]
> We could for example use [ProtectedData](https://learn.microsoft.com/en-us/dotnet/api/system.security.cryptography.protecteddata?redirectedfrom=MSDN&view=windowsdesktop-7.0) class

Ah, didn't notice its Windows-only. Well, libsecret then.

> You're right, but I honestly think it's more of a hassle then it's worth. I'm sure some people will complain saying why do I have to remove the pair if just my password changed and I just wanna change that instead of both username and password on reentry. And other complaints...

It's not a problem to reentry username and password once, so such complaints I would ignore. But if the user regularly downloads from a service that require login all the time, reentering username and password for each download is a hassle.

**Comment by nlogozzo** [comment]
> Well, libsecret then.

I say we should find a C# library to use, that way it would stay cross-platform in the backend and be easier for dependency management as the csharp library will be added from NuGet. 

Maybe something like:
https://github.com/rajanadar/VaultSharp

Or just a simple encryption: https://gist.github.com/pedro2555/85c92ad202cff0f0a096fd1a45d0305e

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/TubeConverter/releases/tag/2023.6.1-beta2

**Comment by mossymossmoss** [comment]
Was this removed? It doesn't seem like this is present in the latest versions of the app

**Comment by fsobolev** [comment]
> Was this removed? It doesn't seem like this is present in the latest versions of the app

There's "Authenticate" option

![image](https://github.com/NickvisionApps/Parabolic/assets/117388856/e9395ec0-264b-42cc-98b2-efc61344336e)

**Comment by dCo3lh0** [comment]
Can somebody teach me how does this function work, i've tried inputting the website URL for the authentication, tried with facebook and odysee, doesn't work in anything, the authentication simply doesn't work, even if the url in the keyring/keychain (its in portuguese here) is the exact login page link for the authentication, it doesn't work.

**Comment by fsobolev** [comment]
> Can somebody teach me how does this function work, i've tried inputting the website URL for the authentication, tried with facebook and odysee, doesn't work in anything, the authentication simply doesn't work, even if the url in the keyring/keychain (its in portuguese here) is the exact login page link for the authentication, it doesn't work.

You don't need to paste URL of login page anywhere, the URL in "Media URL" field is always a link to the video you want to download. I don't know about odysee, but for facebook authentication using cookies should work, look in application's preferences.

**Comment by dCo3lh0** [comment]
> 
> You don't need to paste URL of login page anywhere, the URL in "Media URL" field is always a link to the video you want to download. I don't know about odysee, but for facebook authentication using cookies should work, look in application's preferences.

ok. Just a little point, i'm not talking about this window in the post above that we open to validate the download, before that, i go into hamburguer menu than in my language is called chaveiro, but in english i think its Keychain, than you have add login, in the login window you have:

Name: Facebook (for example)
URL: https://www.facebook.com/login.php
Username: myrealusername
Password: mypassword

after i put these, it should validate the credentials for a user account (it would, but it doesn't).

than after i added this, i go back to the main download window, input in the URL, the direct media URL link, activate the Authenticate switch, select the "Credential from the Keychain" i created in the case facebook, and it should download it, i thought. But it gives me error Certify that the credentials are correct and the Media URL direct link for a video in facebook becomes red, but is the exact direct link to the video, i know for sure i've done right.

**Comment by fsobolev** [comment]
Then my guess is that yt-dlp doesn't support authentication for facebook using login and password (just like it's not supported for youtube for example). Please try using cookies.

**Comment by nlogozzo** [comment]
Yeah for accounts that have two factor authentication, or even email/phone verification like Facebook, logging in with your username and password won't work as @fsobolev said.

You'll have to go to Facebook on your browser and login there. Then you can look the Preferences for `Cookies File`. Click the help icon to get an extension that gets the cookies file for your browser. Once you gave it upload it to Parabolic and then try validating your Facebook media link of the video to download again (no need to enter username and password).
