### ISSUE TITLE
Add "Include Number Tiltle for Playlists" default in Preferences

### ISSUE THREAD

**Issue by Batwam** [NickvisionApps/TubeConverter#324]
While it is possible to do this when selecting the download, activating this behaviour needs to be done each time. 

I was wondering if it would be possible to add "Include Number Titles when downloading Playlists" in Preferences so the user can set this behaviour as default?

Alternatively, it could be remembered as default like it's done for the Download folder location?

**Comment by Batwam** [comment]
While it is possible to do this when selecting the download, I was wondering if it would be possible to add "Include Number Titles when downloading Playlists" in Preferences so the user can set this behaviour as default?

**Comment by nlogozzo** [comment]
> Alternatively, it could be remembered as default

Will probably go this route. If you activate it, it will be remembered and automatically activated for next time. If you deactivate it, it will remember and next times will stay deactivated until you change it again.

**Comment by Batwam** [comment]
yeah, that would be consistent with the current behaviour for Downloads and allow to minimise Preference options.

**Comment by Batwam** [comment]
I would also add that perhaps having this option as a Gtk.Switch directly within the "Add Download" page would make it more accessible?

**Comment by nlogozzo** [comment]
> I would also add that perhaps having this option as a Gtk.Switch directly within the "Add Download" page would make it more accessible?

I think we can make that work :)

**Comment by nlogozzo** [comment]
@Batwam Here we go:
![image](https://github.com/NickvisionApps/TubeConverter/assets/17648453/7f050328-45c5-4da6-93d4-35267197becc)

**Comment by Batwam** [comment]
wow, that was fast. Perhaps call it "Include Number Titles" so it describes an action?

**Comment by nlogozzo** [comment]
> wow, that was fast.

:)

> Perhaps call it "Include Number Titles" so it describes an action?

"Include Number Titles" sounds a little bit weird. I think "Number" is sufficient since it does describe an action, the action of *numbering* the titles.

**Comment by Batwam** [comment]
ok, no worries. Thanks for the quick response, very impressed by how quickly the updates are being released!

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/TubeConverter/releases/tag/2023.6.1-beta2

**Comment by Batwam** [comment]
just tried the new version. it works fine but the button states "Number Video Titles" which is different from what was shown in the screenshot above. As this can be used also for Music titles, wouldn't it makes more sense to keep "Number Titles" as previously planned? or "Number Playlist Titles"?

**Comment by nlogozzo** [comment]
Yeah I see what your saying...I'll change it back to just "Number Titles"
