### ISSUE TITLE
Enable YouTube Chapter Support

### ISSUE THREAD

**Issue by Raxelgrande** [NickvisionApps/TubeConverter#338]
Another app that fulfills the same propose as TubeConverter, VideoDownloader, includes chapters (or timestamps) of downloaded videos. 

Both use yt-dlp to power the program, so TubeConverter can support it. It's especially useful for educational videos that use chapters/timestamps to divide the content. 

I would include a toggle called "Download chapters for supported media".

**Comment by nlogozzo** [comment]
![image](https://github.com/NickvisionApps/TubeConverter/assets/17648453/f633d93a-202a-4e9f-a4cf-74ee4a5852fa)

I'll include a new option here called `Embed Chapters` that you can turn on to enable this feature :)

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/TubeConverter/releases/tag/2023.6.1-beta2

**Comment by rugk** [comment]
Ah so this is `--embed-chapters` of yt-dlp?

**Comment by nlogozzo** [comment]
> Ah so this is `--embed-chapters` features of yt-dlp?

Correct. You should find the setting in the apps preferences under Converter section.
