### ISSUE TITLE
Retry failed downloads

### ISSUE THREAD

**Issue by Batwam** [NickvisionApps/TubeConverter#343]
Hi, me again, I was wondering if it would be possible for TubeConverter to retry up to X many times failed downloads, with X being set in preferrences (perhaps with a default like 2 and max maxum 10).

It's pretty ocmmon (for me ) to have downloads fail but when I try again, they work. it would be ideal if this was done automatically.

**Comment by nlogozzo** [comment]
I'm sure this is possible, but I don't think its the best thing to implement UI/UX wise.

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/TubeConverter/issues/310#issuecomment-1585770592

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/TubeConverter/releases/tag/2023.6.1-rc1
