### ISSUE TITLE
Automatically sort Music into subfolders `Artist/Album`

### ISSUE THREAD

**Issue by Batwam** [NickvisionApps/TubeConverter#344]
I was also wondering, would it be within scope potentially for TubeConverter to sort music Downloads into subfolders like Artist/Album? or is this not possible and/or better handled separately?

It could be possible to simply have it done as Artist/Album. If you want more options, there could be a drop down to choose from various options (like in Rhythmbox preferences).

**Comment by nlogozzo** [comment]
This is definitely not in the scope of Tube Converter. Sounds more like a feature we could implement in Tagger.

**Comment by Batwam** [comment]
for the record, I found `mussort` which does this simple task of sorting by Artist/Album using command line. Just need to type `mussort .` in the folder. Not that it will also rename the files and replace spaces with `_`.

More info: https://manpages.ubuntu.com/manpages/trusty/man1/mussort.1.html
