### ISSUE TITLE
Make the app show up when one searches for "youtube" or "downloader" in the menu

### ISSUE THREAD

**Issue by apandada1** [NickvisionApps/TubeConverter#353]
It would be great if the app shows up in the menu when one searcher for `youtube` and `downloader`.

This can be achieved by adding the following line to the .desktop file, like [this](https://github.com/rafaelmardojai/blanket/blob/408ca93599d32fb899e9262e1f10508e7dca6993/data/com.rafaelmardojai.Blanket.desktop.in#L9)
```
Keywords=YouTube;Downloader;
```

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/TubeConverter/releases/tag/2023.6.1-rc1

**Comment by apandada1** [comment]
I installed Tube Converter a few days ago after seeing it in OMG Ubuntu. I recently wanted to download an youtube video, but could not find this app in the menu because I forgot its name (never having used it). I searched for YouTube in the menu, and it still did not show up. That's why I decided to send this pull request.

Thank you for creating this app :grinning:
