### ISSUE TITLE
File names are truncated if the user-specified name contains a dot

### ISSUE THREAD

**Issue by paulmcauley** [NickvisionApps/TubeConverter#358]
If the user-specified file name contains a dot, then the file that is saved on disk will be truncated at the dot.

**Comment by nlogozzo** [comment]
Could you provide the link and where you placed the `dot`? I can't seem to reproduce...

I took this URL:
Placed a dot between `Death` and `of`:
![image](https://github.com/NickvisionApps/TubeConverter/assets/17648453/aaba8079-4d27-4807-b4ce-4302177aeed5)
And it was downloaded correctly:
![image](https://github.com/NickvisionApps/TubeConverter/assets/17648453/1a5ca21a-09c3-4838-a0c0-635bba355426)

**Comment by paulmcauley** [comment]
https://youtu.be/pmXqBqhikTc

**Comment by nlogozzo** [comment]
![image](https://github.com/NickvisionApps/TubeConverter/assets/17648453/4b042096-152a-41f5-9d31-1d4bfe69f31c)

Worked fine for me on both V2023.6.0 and V2023.6.1-beta2 ... what version of Tube Converter are you using?
Also, when in the `About` dialog, could you click `Troubleshooting` -> `Debugging Information` and copy that text and paste it here as well...

**Comment by nlogozzo** [comment]
> audio only, "disallow conversions" selected

Just saw this edit, even with that it still works for me 😅
![image](https://github.com/NickvisionApps/TubeConverter/assets/17648453/85122ca0-799c-491b-b855-308b7ea0b3b4)

**Comment by nlogozzo** [comment]
Ah wait...on V2023.6.0 it doesn't work with `Disallow Conversion`, with V2023.6.1-beta2 it does...

Could you try this: [V2023.6.1-beta2](https://github.com/NickvisionApps/TubeConverter/releases/tag/2023.6.1-beta2) and let me know if it fixes it.

**Comment by paulmcauley** [comment]
I have "disallow conversions" selected, so you should get an .opus:
![Screenshot_20230613_031558](https://github.com/NickvisionApps/TubeConverter/assets/6924479/3f22fe7b-401a-4d8a-88c1-fc4d563730b8)

2023.6.0 Flatpak, KDE Plasma 5.27, OpenSUSE Leap 15.5

org.nickvision.tubeconverter
2023.6.0
GTK 4.10.3
libadwaita 1.3.2
Flatpak
yt-dlp 2023.03.04
ffmpeg version 6.0
aria2 version 1.36.0
en-GB
LANG=en_GB.UTF-8
LC_CTYPE="en_GB.UTF-8"
LC_NUMERIC="en_GB.UTF-8"
LC_TIME="en_GB.UTF-8"
LC_COLLATE="en_GB.UTF-8"
LC_MONETARY="en_GB.UTF-8"
LC_MESSAGES="en_GB.UTF-8"
LC_PAPER="en_GB.UTF-8"
LC_NAME="en_GB.UTF-8"
LC_ADDRESS="en_GB.UTF-8"
LC_TELEPHONE="en_GB.UTF-8"
LC_MEASUREMENT="en_GB.UTF-8"
LC_IDENTIFICATION="en_GB.UTF-8"
LC_ALL=

**Comment by nlogozzo** [comment]
> I have "disallow conversions" selected, so you should get an .opus: ![Screenshot_20230613_031558](https://user-images.githubusercontent.com/6924479/245332480-3f22fe7b-401a-4d8a-88c1-fc4d563730b8.png)

See https://github.com/NickvisionApps/TubeConverter/issues/358#issuecomment-1588414709

**Comment by paulmcauley** [comment]
> Ah wait...on V2023.6.0 it doesn't work with `Disallow Conversion`, with V2023.6.1-beta2 it does...
> 
> Could you try this: [V2023.6.1-beta2](https://github.com/NickvisionApps/TubeConverter/releases/tag/2023.6.1-beta2) and let me know if it fixes it.

I can confirm it works OK in V2023.6.1-beta2

**Comment by nlogozzo** [comment]
Great! V2023.6.1 stable will be released this Friday :)
