### ISSUE TITLE
[Feature Request] Select URL in add download by default

### ISSUE THREAD

**Issue by hyuri** [NickvisionApps/TubeConverter#363]
Hi!

**Suggestion:**
It would be nice if, when we add a new download, the URL that is automatically pasted is also automatically selected by default. That way, if we accidentally paste (Ctrl + V), it just replaces the URL that's already there.

**Comment by nlogozzo** [comment]
Great idea! I've definitely ended up with two identical URLs pasted next to each other from this!

**Comment by nlogozzo** [comment]
You suggested this right after I released `rc1` of V2023.6.1 😅 
But it will be included in the stable release on Friday :)

**Comment by hyuri** [comment]
😂 Awesome!

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/TubeConverter/releases/tag/2023.6.1
