### ISSUE TITLE
Program crashes upon verification

### ISSUE THREAD

**Issue by Hyruleh3ro** [NickvisionApps/TubeConverter#373]
### **Summary:** 
When I try to download a private playlist on youtube with the newly added feature of authentication the program crashes.

### **System specifications:**
Windows 11
Windows-Subsystem Linux Version 2 (WSL2) (Current version of WSL2 as far as I can tell)
Current version of TubeConverter (2023.6.1)

### **Procedure:**
I enter the link to the privately created youtube-playlist in the media URL space, then activate 'Authenticate' enter the email-address to my account (I even tried it without the @gmail.com ending as you can also do that normally when logging into a youtube account) and then finally add my password. After that I press verify and the button turns into a loading-symbol and shortly afterwards the entire program crashes. Shortly afterwards I attempted to intentionally cause an error/test another error-prone case by toggling authenticate and leaving every space empty, but this causes the program to crash as well. After further testing I was able to verify in which combinations the program does work and in which it doesn't (only regarding youtube):

**Works:**

-normal video link (with and without toggled authentication (username and password left blank))
-normal playlist link (with and without toggled authentication (username and password left blank))
-unlisted video (that even required age verification by youtube, but didn't require authentication in the downloader)

**Crashes:**

-Every space left blank (while authenticate is toggled) 
-Private Playlist link (playlist created by me with my youtube account; authenticate toggled and login data for youtube entered)

(Annotation: I was able to see some type of control symbol in the youtube link during testing, but as this only happened twice and I am currently incapable of replicating the appearance of this symbol I don't know if this of any significance. The error certainly also happened in every situation without that symbol)
If needed I can provide additional photos and screenshots, but I think that these won't give any further insights.
Thank you for your time and efforts.

**Comment by nlogozzo** [comment]
> Private Playlist link (playlist created by me with my youtube account; authenticate toggled and login data for youtube entered)

So, with YouTube, because it uses Google OAuth,  you can not just specify your Google username and password...it won't work. For YouTube authentication, you'd probably need to upload a cookies file in Preferences. 

Alternatively, you could create a google app password (https://support.google.com/mail/answer/185833?hl=en) and use your email and that new app password in the authentication fields.
^ for that I'd also recommend also storing it in Tube Converter's keyring as the generated app password is usually a random string of characters that would be hard to remember.

**Comment by nlogozzo** [comment]
Let me know if either of those options work for you.

**Comment by nlogozzo** [comment]
@fsobolev maybe it would be good to create docs for this? And also move all our little tooltips everywhere into these new docs?

**Comment by Hyruleh3ro** [comment]
Ok. I will check out that solution shortly, but from a development perspective I'd suggest, that those errors should still be catched to avoid a total crash of the program if possible.

**Comment by nlogozzo** [comment]
Yes agreed. Do you happen to have the output from the terminal when it crashed? That should tell us the exact line of where to catch the error.

**Comment by Hyruleh3ro** [comment]
So the first error message (all spaces left blank):

Unhandled exception. System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at NickvisionTubeConverter.GNOME.Views.AddDownloadDialog.ValidateOptions() in /run/build/org.nickvision.tubeconverter/NickvisionTubeConverter.GNOME/Views/AddDownloadDialog.cs:line 498
   at NickvisionTubeConverter.GNOME.Views.AddDownloadDialog.FinishSearchUrl() in /run/build/org.nickvision.tubeconverter/NickvisionTubeConverter.GNOME/Views/AddDownloadDialog.cs:line 482
   at NickvisionTubeConverter.GNOME.Views.AddDownloadDialog.<.ctor>b__65_1(IntPtr x) in /run/build/org.nickvision.tubeconverter/NickvisionTubeConverter.GNOME/Views/AddDownloadDialog.cs:line 118

**Comment by Hyruleh3ro** [comment]
Ok. It seems that the same error is triggered each time, so therefore I can't post any more error-messages as it is the same every time (the same as the one posted above).

**Comment by Hyruleh3ro** [comment]
Hi. I just wanted to give you a quick update regarding your solution(s). I tried the first one with the extension that is recommended in the TubeConverter code (Annotation: The question mark in the program next to cookie file, which would lead you to the extension, doesn't work in my configuration/doesn't show any recommended extensions for the cookie file). I added the cookie-File and despite this, the program caused the same error (resulting in a crash) as mentioned before and therefore this solution unfortunately doesn't work. Despite this I just want to say that I circumvented the problem by creating a youtube channel, which enables me to set the playlist to unlisted. Afterwards I simply downloaded it with tube-converter without further problems.

**Comment by nlogozzo** [comment]
Could you download and install the flatpak or snap artifact from [this CI build](https://github.com/NickvisionApps/TubeConverter/actions/runs/5301209823) (or if you built and installed manually [use this PR](https://github.com/NickvisionApps/TubeConverter/pull/376)) and test if the program crashes anymore with the scenarios above? It shouldn't crash anymore and instead notify you that the credentials are invalid.

**Comment by nlogozzo** [comment]
I've created a beta release to make it easier for you to test:
https://github.com/NickvisionApps/TubeConverter/releases/tag/2023.6.2-beta1

**Comment by schustobias** [comment]
@nlogozzo Hi. I tested the following use-cases with the beta:
_-all spaces blank
-non-accessible url (without authentication active)
-non-accessible url (with authentication active and no authentication data)
-non-accessible url (with authentication active and wrong authentication data)_

All of them resulted in the following error (and the program crashed as well each time):
**(This error is not the same as before)**

Unhandled exception. System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at NickvisionTubeConverter.GNOME.Views.AddDownloadDialog.ValidateOptions() in /run/build/org.nickvision.tubeconverter/NickvisionTubeConverter.GNOME/Views/AddDownloadDialog.cs:line 505
   at NickvisionTubeConverter.GNOME.Views.AddDownloadDialog.FinishSearchUrl() in /run/build/org.nickvision.tubeconverter/NickvisionTubeConverter.GNOME/Views/AddDownloadDialog.cs:line 489
   at NickvisionTubeConverter.GNOME.Views.AddDownloadDialog.<.ctor>b__65_1(IntPtr x) in /run/build/org.nickvision.tubeconverter/NickvisionTubeConverter.GNOME/Views/AddDownloadDialog.cs:line 118

**Comment by Hyruleh3ro** [comment]
@nlogozzo Hi. I tested the following use-cases with the beta:
_-all spaces blank
-non-accessible url (without authentication active)
-non-accessible url (with authentication active and no authentication data)
-non-accessible url (with authentication active and wrong authentication data)_

All of them resulted in the following error (and the program crashed as well each time):
**(This error is not the same as before)**

Unhandled exception. System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
at System.Collections.Generic.List`1.get_Item(Int32 index)
at NickvisionTubeConverter.GNOME.Views.AddDownloadDialog.ValidateOptions() in /run/build/org.nickvision.tubeconverter/NickvisionTubeConverter.GNOME/Views/AddDownloadDialog.cs:line 505
at NickvisionTubeConverter.GNOME.Views.AddDownloadDialog.FinishSearchUrl() in /run/build/org.nickvision.tubeconverter/NickvisionTubeConverter.GNOME/Views/AddDownloadDialog.cs:line 489
at NickvisionTubeConverter.GNOME.Views.AddDownloadDialog.<.ctor>b__65_1(IntPtr x) in /run/build/org.nickvision.tubeconverter/NickvisionTubeConverter.GNOME/Views/AddDownloadDialog.cs:line 118

**Comment by swick** [comment]
I currently get the some exception, even in the flathub-beta channel. It's reproducible easily with any input to the Media URL field which doesn't seem to get handled, e.g. empty, the string "x", whatever really.

This issue is much more general.

**Comment by nlogozzo** [comment]
Ok @Hyruleh3ro and @swick you're crashing issues should be fixed in [V2023.6.2-beta2](https://github.com/NickvisionApps/TubeConverter/releases/tag/2023.6.2-beta2) .  (*The build is currently being uploaded to `flathub-beta`...should be available within a half-an-hour. Make sure you are running beta2 before testing if the crashes have been fixed for good*) :)

I also made it where the `Validate` button will be disabled until a URL is entered into the row:
![image](https://github.com/NickvisionApps/TubeConverter/assets/17648453/9cfe3014-fb3b-4924-a4e1-d7c8b565cf6e)
![image](https://github.com/NickvisionApps/TubeConverter/assets/17648453/7dc26f59-6037-48c4-8dfc-e7de072c09c1)

**Comment by swick** [comment]
Thanks, the crash is fixed and the validate button behaves as explained.
