### ISSUE TITLE
view log button freeze when contains a lot of output

### ISSUE THREAD

**Issue by gmankab** [NickvisionApps/TubeConverter#375]
fedora, flatpak, 2023.6.1

how to reproduce - https://youtu.be/iSB9psZlnk8

**Comment by nlogozzo** [comment]
I think we need to use a TextView instead of a Label

**Comment by nlogozzo** [comment]
[Screencast from 2023-06-16 23-35-42.webm](https://github.com/NickvisionApps/TubeConverter/assets/17648453/f514a99e-c9e9-493d-99aa-ea143911de28)

Using a Gtk.TextView seems to be a lot more stable...

**Comment by nlogozzo** [comment]
Can you download and install the flatpak or snap artifact from [this CI build](https://github.com/NickvisionApps/TubeConverter/actions/runs/5296151704) and test the fix before we merge?

**Comment by nlogozzo** [comment]
I've created a beta release to make it easier for you to test:
https://github.com/NickvisionApps/TubeConverter/releases/tag/2023.6.2-beta1
