### ISSUE TITLE
Keyring label is a bit cut off

### ISSUE THREAD

**Issue by rene-coty** [NickvisionApps/TubeConverter#379]
Just a tiny UI papercut: the "Enable" label in the "Keyring" window seems a bit cut off when the window opens, see screnshots below:
![Capture d’écran du 2023-06-18 17-51-12](https://github.com/NickvisionApps/TubeConverter/assets/95506494/4a67085e-29c2-419b-aecb-b854831102b5)
![Capture d’écran du 2023-06-18 17-51-06](https://github.com/NickvisionApps/TubeConverter/assets/95506494/e5f06d78-5892-4c3d-a46d-0b2c146d9f19)

---
org.nickvision.tubeconverter
2023.6.1
GTK 4.10.3
libadwaita 1.3.2
Flatpak
yt-dlp 2023.03.04
psutil 5.9.5
ffmpeg version 6.0
aria2 version 1.36.0
fr-FR
LANG=fr_FR.UTF-8
LC_CTYPE="fr_FR.UTF-8"
LC_NUMERIC="fr_FR.UTF-8"
LC_TIME="fr_FR.UTF-8"
LC_COLLATE="fr_FR.UTF-8"
LC_MONETARY="fr_FR.UTF-8"
LC_MESSAGES="fr_FR.UTF-8"
LC_PAPER="fr_FR.UTF-8"
LC_NAME="fr_FR.UTF-8"
LC_ADDRESS="fr_FR.UTF-8"
LC_TELEPHONE="fr_FR.UTF-8"
LC_MEASUREMENT="fr_FR.UTF-8"
LC_IDENTIFICATION="fr_FR.UTF-8"
LC_ALL=

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/TubeConverter/releases/tag/2023.6.2-beta2

![image](https://github.com/NickvisionApps/TubeConverter/assets/17648453/57707d39-710c-4b93-8a72-b92f290c64d4)
