### ISSUE TITLE
Add Yelp Docs

### ISSUE THREAD

**Issue by nlogozzo** [NickvisionApps/TubeConverter#385]

**Comment by soumyaDghosh** [comment]
Snap's not gonna help with this soon, so, I guess I'll need to disable it for snaps.

**Comment by nlogozzo** [comment]
Is it disabled for `Denaro`? It will basically be the same infrastructure that Denaro uses...

**Comment by soumyaDghosh** [comment]
Not now, but I'll. Snap's support for yelp tool is kinda controversial. It's more of a Gnome fault. The gnome guys made it some how to work with flatpak. But, hopefully, as I talked with KenVandine, there is some hope for it.

**Comment by nlogozzo** [comment]
> The gnome guys made it some how to work with flatpak

How so? Cause for me it works both with flatpak and if I install denaro manually from AUR or from source, docs still get installed.

**Comment by soumyaDghosh** [comment]
Withdrew my last words, cause I spoke it wrong. It's the background apps thing, regarding yelp, I have no idea, but, I will give it another last try soon. And yes, Ken sir said to me that there can be some work done in the gnome-sdk for this. All issue is with the snap confinement. In current scenario, when you call the yelp, it calls yelp in flatpak denaro which is in the gnome-sdk, but for the case of snap it calls the deb yelp. So, it can't fetch the docs.
