### ISSUE TITLE
URL failing to validate

### ISSUE THREAD

**Issue by swick** [NickvisionApps/TubeConverter#386]
The url `https://www.zdf.de/show/mai-think-x-die-show/maithink-x-folge-23-100.html` fails to validate but works fine with youtube-dl.

**Comment by nlogozzo** [comment]
Got it fixed!
![image](https://github.com/NickvisionApps/TubeConverter/assets/17648453/a8a975c1-2930-48ea-a3f8-6cf65789b8f1)

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/TubeConverter/releases/tag/2023.6.2-rc1

**Comment by swick** [comment]
Thanks, can confirm, it's fixed.
